//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFtest.eCATWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataSnapShot", Namespace="http://www.grgbanking.com/product/eCAT3")]
    [System.SerializableAttribute()]
    public partial class DataSnapShot : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WCFtest.eCATWCF.DataSnapShotItem[] ItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFtest.eCATWCF.DataSnapShotItem[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataSnapShotItem", Namespace="http://www.grgbanking.com/product/eCAT3")]
    [System.SerializableAttribute()]
    public partial class DataSnapShotItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFtest.eCATWCF.DataCacheType TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFtest.eCATWCF.DataCacheType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataCacheType", Namespace="http://schemas.datacontract.org/2004/07/eCATInspectorSerivceProtocol")]
    public enum DataCacheType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Transaction = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CardHolder = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Terminal = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Workflow = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.grgbanking.com/product/eCAT3R2", ConfigurationName="eCATWCF.IeCATInspectorService", CallbackContract=typeof(WCFtest.eCATWCF.IeCATInspectorServiceCallback))]
    public interface IeCATInspectorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.grgbanking.com/product/eCAT3R2/IeCATInspectorService/LoginIn", ReplyAction="http://www.grgbanking.com/product/eCAT3R2/IeCATInspectorService/LoginInResponse")]
        bool LoginIn(out int argAccessToken, string argAccount, string argPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.grgbanking.com/product/eCAT3R2/IeCATInspectorService/LoginOff", ReplyAction="http://www.grgbanking.com/product/eCAT3R2/IeCATInspectorService/LoginOffResponse")]
        bool LoginOff(int argAccessToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.grgbanking.com/product/eCAT3R2/IeCATInspectorService/QuerySnapshotOfDa" +
            "ta", ReplyAction="http://www.grgbanking.com/product/eCAT3R2/IeCATInspectorService/QuerySnapshotOfDa" +
            "taResponse")]
        WCFtest.eCATWCF.DataSnapShot QuerySnapshotOfData(int argAccessToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.grgbanking.com/product/eCAT3R2/IeCATInspectorService/ListenDataChanged" +
            "", ReplyAction="http://www.grgbanking.com/product/eCAT3R2/IeCATInspectorService/ListenDataChanged" +
            "Response")]
        bool ListenDataChanged(int argAccessToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.grgbanking.com/product/eCAT3R2/IeCATInspectorService/UnlistenDataChang" +
            "ed", ReplyAction="http://www.grgbanking.com/product/eCAT3R2/IeCATInspectorService/UnlistenDataChang" +
            "edResponse")]
        bool UnlistenDataChanged(int argAccessToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.grgbanking.com/product/eCAT3R2/IeCATInspectorService/Hearbeat", ReplyAction="http://www.grgbanking.com/product/eCAT3R2/IeCATInspectorService/HearbeatResponse")]
        void Hearbeat(int argAccessToken);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IeCATInspectorServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.grgbanking.com/product/eCAT3R2/IeCATInspectorService/OnDataChanged")]
        void OnDataChanged(string argKey, string argValue, WCFtest.eCATWCF.DataCacheType argType, string argDateTime);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.grgbanking.com/product/eCAT3R2/IeCATInspectorService/OnDataDeleted")]
        void OnDataDeleted(string argKey, WCFtest.eCATWCF.DataCacheType argType, string argDateTime);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.grgbanking.com/product/eCAT3R2/IeCATInspectorService/OnDataCacheClear")]
        void OnDataCacheClear(WCFtest.eCATWCF.DataCacheType argType, string argDateTime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IeCATInspectorServiceChannel : WCFtest.eCATWCF.IeCATInspectorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IeCATInspectorServiceClient : System.ServiceModel.DuplexClientBase<WCFtest.eCATWCF.IeCATInspectorService>, WCFtest.eCATWCF.IeCATInspectorService {
        
        public IeCATInspectorServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public IeCATInspectorServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public IeCATInspectorServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public IeCATInspectorServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public IeCATInspectorServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public bool LoginIn(out int argAccessToken, string argAccount, string argPassword) {
            return base.Channel.LoginIn(out argAccessToken, argAccount, argPassword);
        }
        
        public bool LoginOff(int argAccessToken) {
            return base.Channel.LoginOff(argAccessToken);
        }
        
        public WCFtest.eCATWCF.DataSnapShot QuerySnapshotOfData(int argAccessToken) {
            return base.Channel.QuerySnapshotOfData(argAccessToken);
        }
        
        public bool ListenDataChanged(int argAccessToken) {
            return base.Channel.ListenDataChanged(argAccessToken);
        }
        
        public bool UnlistenDataChanged(int argAccessToken) {
            return base.Channel.UnlistenDataChanged(argAccessToken);
        }
        
        public void Hearbeat(int argAccessToken) {
            base.Channel.Hearbeat(argAccessToken);
        }
    }
}
